### ISSUE TITLE
Case of Adafruit_CPlay_NeoPixel.h in Adafruit_CircuitPlayground.h

### ISSUE THREAD

**Issue by alwayslinux2** [adafruit/Adafruit_CircuitPlayground#1]
The #include in Adafruit_CircuitPlayground.h for Adafruit_CPlay_NeoPixel.h (line 18) calls for Adafruit_CPlay_Neopixel.h  (lower case p) which doesn't find the file on case sensitive file systems (Linux)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_CircuitPlayground/commit/7eae36a509c436defdf4c6813cfedd2d2cb7e23f

should be fixied!

**Comment by kailando** [comment]
Lucky to be issue #1 or [issue 1](https://github.com/adafruit/Adafruit_CircuitPlayground/issues/1)
