### ISSUE TITLE
'analogPinToChannel' not declared in scope : Adafruit_CPlay_Mic.cpp

### ISSUE THREAD

**Issue by monsieurDavid** [adafruit/Adafruit_CircuitPlayground#14]
- Arduino board:  Circuit PlayGround Dev. Edition
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.12
- Steps to reproduce the problem:
Compile and upload `~/Arduino/libraries/Adafruit_Circuit_Playground/examples/demo.ino`

```
~/Arduino/libraries/Adafruit_Circuit_Playground/utility/Adafruit_CPlay_Mic.cpp: In member function 'int Adafruit_CPlay_Mic::peak(uint16_t)':
~/Arduino/libraries/Adafruit_Circuit_Playground/utility/Adafruit_CPlay_Mic.cpp:27:37: error: 'analogPinToChannel' was not declared in this scope
   channel     = analogPinToChannel(4); // Pin A4 to ADC channel
                                     ^
~/Arduino/libraries/Adafruit_Circuit_Playground/utility/Adafruit_CPlay_Mic.cpp: In member function 'void Adafruit_CPlay_Mic::capture(int16_t*, uint8_t)':
~/Arduino/libraries/Adafruit_Circuit_Playground/utility/Adafruit_CPlay_Mic.cpp:84:37: error: 'analogPinToChannel' was not declared in this scope
   channel     = analogPinToChannel(4); // Pin A4 to ADC channel
                                     ^
exit status 1
Error compiling for board Arduino/Genuino Uno.
```

**Comment by monsieurDavid** [comment]
My mistake - was uploading to wrong board. Nothing to see. Move along.

**Comment by sigmus731** [comment]
What exactly do you mean by saying the wrong board?
Sorry, but i'm just starting to learn about arduino programming.

**Comment by jtrombone** [comment]
I found that on my Bare-Bones board (I use the Arduino/Genuino Uno board option I just had to comment out the line:
//#include <Adafruit_Circuit_Playground.h>
I believe this line is for the specific Adafruit board
Also had to add the average.h header file in the sketch folder
Found the header file here: 
https://github.com/MajenkoLibraries/Average/blob/master/Average.h
