### ISSUE TITLE
Add a switch off feature for Accelerometer mouse code.

### ISSUE THREAD

**Issue by FOSSBOSS** [adafruit/Adafruit_CircuitPlayground#23]
This is a recommendation for ease of use, regarding the accelerometer mouse code. Once a user codes the mouse, reprogramming the circuit playground can be difficult, forcing the user to then use the mouse to navigate the IDE.  This was my experience, and I think other users may have the same issue. The problem could easily be resolved, by including the lines:
....
  if (!CircuitPlayground.slideSwitch()) {
    return;
  }
...

in then the users will have a way to regain normal mouse operations. 
Source here:
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/master/examples/accel_mouse/accel_mouse.ino

**Comment by ReanimationXP** [comment]
It appears this change has been added but this issue wasn't closed.
