### ISSUE TITLE
Example programs broken

### ISSUE THREAD

**Issue by xhozt** [adafruit/Adafruit_CircuitPlayground#31]
- Arduino board:  **Circuit playground**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.5**

- Current example programs are broken . All generate errors on compile example shown in attached TXT
[New Text Document (4).txt](https://github.com/adafruit/Adafruit_CircuitPlayground/files/1723378/New.Text.Document.4.txt)

**Comment by ladyada** [comment]
these are not errors, they are warnings you can ignore!
