### ISSUE TITLE
Adafruit_SleepyDog.h not found when compiling megademo example.

### ISSUE THREAD

**Issue by ReanimationXP** [adafruit/Adafruit_CircuitPlayground#36]
- Arduino board:  **Adafruit Circuit Playground Classic**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.6** (Hourly)

When flashing the Circuit Playground library's [megademo](https://github.com/adafruit/Adafruit_CircuitPlayground/blob/cc82c9165066b80afb715eb46153a85857fd5f20/examples/mega_demo/mega_demo.ino) example, I was presented with an error citing that `Adafruit_SleepyDog.h` was missing. After searching the github I only see it referenced one other place, which is [.travis.yml](https://github.com/adafruit/Adafruit_CircuitPlayground/blob/abc0cad00459656f402945df6b89287a7d678297/.travis.yml). Specifically:

```
install:
   - arduino --install-library "Adafruit LED Backpack Library","Adafruit GFX Library","Adafruit SleepyDog Library","Adafruit Zero FFT Library"
```

I checked my libraries and found that `Adafruit SleepyDog Library` was not installed, despite having just recently installed the Adafruit Circuit Playground library.  I tried deleting the Playground library and then reinstalling it, which worked fine, but SleepyDog still was not present. Only after searching for it manually in the library manager and installing it did megademo compile and flash correctly.

I'd venture to guess something is going wrong with the install script. I wasn't aware libraries could even install other libraries as dependencies. I assume that's what's supposed to be happening here and that'd be a neat and interesting feature if it worked :) Ideas?

My hourly is a bit old but it's still newer than the latest release:
`1.8.6 Hourly Build 2018/04/19 10:37`

**Comment by ReanimationXP** [comment]
Also worth noting that other libraries here like LED Backpack Library were also not installed.

**Comment by ladyada** [comment]
hi it's mentioned here! :)
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/cc82c9165066b80afb715eb46153a85857fd5f20/examples/mega_demo/mega_demo.ino#L13

**Comment by ReanimationXP** [comment]
Okay, but why is it mentioned in the `-install-library` flag then?

**Comment by ladyada** [comment]
thats so travis can compile things, you can read about it here
https://learn.adafruit.com/the-well-automated-arduino-library

**Comment by ReanimationXP** [comment]
Ah, thanks. Found it after posting. Didn't occur to me it'd have nothing to do with Arduino. Thanks :)
