### ISSUE TITLE
redLed() no longer working for CPC

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPlayground#40]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=58&t=152174

Seems to be related to low level register writes and timer setup in `Adafruit_CPlay_Speaker::begin()`: 
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/991fd39f8860a7fed0e08b7fb6d69192b022c783/utility/Adafruit_CPlay_Speaker.cpp#L18-L29

**Comment by ladyada** [comment]
if you remove that section, does the LED start working? :/

**Comment by caternuson** [comment]
Yep.

Looks like OC4A is on D13:
![image](https://user-images.githubusercontent.com/8755041/58517485-643be080-8160-11e9-9f40-d5ed09e7dfbb.png)

**Comment by ladyada** [comment]
dya mind checking the DS to see if we have a way to disable PWM output on OC4A

**Comment by caternuson** [comment]
Not seeing an option to have only the complementary output (SPEAKER) connected. Only option to disconnect OC4A is to disconnect both:
![image](https://user-images.githubusercontent.com/8755041/58517884-d234d780-8161-11e9-94ca-bfa062b7628e.png)

That init section was moved from another location with this commit:
https://github.com/adafruit/Adafruit_CircuitPlayground/commit/f3694f46be6626ccdacad050bb598770c99b8f36

Maybe there's no need for the call to `speaker.begin()` call the c-tor anymore? `playSound()` will call it?

**Comment by ladyada** [comment]
yep remove it - CPC's are not very popular anymore

**Comment by caternuson** [comment]
Fixed by #41
