### ISSUE TITLE
Preprocessor mismatch for CPX

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPlayground#44]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=58&t=157171

Simple issue. Just some preprocessor stuff.

Recent updates added `#if` that uses `__SAMD21__` 
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/f2b5e28023c81321a477ec06b4ccc3a43624fe44/Adafruit_CircuitPlayground.cpp#L53
vs. BSP which uses `__SAMD21G18A__`
https://github.com/adafruit/ArduinoCore-samd/blob/a6e9eb3686c0899221d2f81829f0b267b2e69240/boards.txt#L184
so pulldown/ups aren't being engaged.

**Comment by ladyada** [comment]
oof sorry about that - i tested CPB the most... could you submit a PR? im a bit swamped today :)

**Comment by caternuson** [comment]
Fixed with #45
