### ISSUE TITLE
Arduino Updater is always showing 1.86 New Version available

### ISSUE THREAD

**Issue by electronic-cosmos** [adafruit/Adafruit_CircuitPlayground#46]
Header say everything :-)
Something is wrong in this version history.
Pleas check it, THX!

**Comment by ladyada** [comment]
please post a screenshot

**Comment by MartinL1** [comment]
@ladyada It's happening with my Arduino IDE Library Manager as well:

![Library Manager](https://user-images.githubusercontent.com/31612615/68043125-7e0fbf80-fccc-11e9-956d-8944aee77801.png)

**Comment by ladyada** [comment]
is this new or has always been happening?

**Comment by MartinL1** [comment]
I'd say about a couple of weeks or so.

**Comment by ladyada** [comment]
that is quite odd because the version number matches the release ... only thing that is new in the last few weeks is we went from 1.9.1 to 1.10.1 - i wonder if the parsing code for semver doesnt handle 2-digit minor numbers (kinda doubt thats it...)

@cmaglie do you have any ideas?

**Comment by MartinL1** [comment]
I think I know what's happening. My Arduino IDE's got two copies of the Adafruit Circuit Python library. 

One, version 1.6.7 (judging by its library.properties file) is located at:

C:\Users\Computer\Documents\Arduino\libraries\Adafruit_Circuit_Playground

The other, version 1.8.6 is in the directory:

C:\Program Files (x86)\Arduino\libraries\Adafruit_Circuit_Playground

Removing the 1.6.7 version allows the Arduino IDE to correctly update to version 1.10.1.

**Comment by MartinL1** [comment]
The updated 1.10.1 library is then correctly created in the directory:

C:\Users\Computer\Documents\Arduino\libraries\Adafruit_Circuit_Playground

**Comment by electronic-cosmos** [comment]
For Mac users? What do  I have to do???

**Comment by MartinL1** [comment]
I'm not a Mac user, but it might be located in the "libraries" directory where your Arduino sketches are located. In the "libraries" directory there should be "Adafruit_Circuit_Python" folder.

Failing that, it should be possible to search for the folder, to find its location.

**Comment by electronic-cosmos** [comment]
I found it. 
1. Enter the Arduino package on mac Program folder.
2. go to: content/Java/libraries/Adafruit_Circuit_Playground
3. removing it.
4. also removing it in documents/Arduino/libraries/Adafruit_Circuit_Playground
5. Starting Arduino IDE again than like mentioned 1.10.1 is installed :-)
THX

**Comment by electronic-cosmos** [comment]
Ups after updating the Adafruit_Circuit_Playground in the libraries manager.
Greetings from Reutlingen Germany
Michael J.
