### ISSUE TITLE
Package discription is no longer accurate.

### ISSUE THREAD

**Issue by easytarget** [adafruit/Adafruit_CircuitPlayground#57]
Library Description is incorrect. From `library.properties`:
```
sentence=All in one library to control Adafruit's Circuit Playground board.
paragraph=All in one library to control Adafruit's Circuit Playground board.  Requires no other dependencies and exposes all Circuit Playground components in a simple to use class.

```
commit: 9b216be8f76d30a5aeb5f6d2db4e096b1be00742 added a `depends=` line to `library.properties`, creating six dependencies, which in turn bring in an even larger tree of sub-dependencies.

The description is no longer accurate and should be changed to reflect this.

**Comment by ladyada** [comment]
technically, those libraries are only used for demos and the library works without em! we can update that line

@siddacious wanna remove it?

**Comment by easytarget** [comment]
It was just an observation on my part, the friggin library mangler in the Arduino IDE is so darn slow that I've spent more time than is good for me staring at this description, it was starting to give me a nervous tic. ;-)

**Comment by siddacious** [comment]
This is fixed in the most recent release!
