### ISSUE TITLE
Capacitive Touch

### ISSUE THREAD

**Issue by TheKitty** [adafruit/Adafruit_CircuitPlayground#7]
- Arduino board:  Circuit Playground Rev B

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6.8

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**
There is no clear method for using the capacitive touch feature.  You can define which pins to set for capacitive, does one need to do the send/receive like in the Teensy and AP pages?  I've got a great Simon game ready but reading the capacitive pads is wonky, they are reading themselves.  Thanks!

**Comment by ladyada** [comment]
try the demo! :)
https://github.com/adafruit/Adafruit_CircuitPlayground/blob/master/examples/demo/demo.ino#L27
